//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANİCİLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANİCİLAR()
        {
            this.Kayitlar = new HashSet<Kayitlar>();
        }
    
        public int kullanıcı_id { get; set; }
        public string kullanıcı_ad { get; set; }
        public string kullanıcı_soyad { get; set; }
        public string kullanıcı_tc { get; set; }
        public string kullanıcı_mail { get; set; }
        public string kullanıcı_telefon { get; set; }
        public Nullable<double> kullanıcı_ceza { get; set; }
        public string kullanıcı_cinsiyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayitlar> Kayitlar { get; set; }
    }
}
