//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int personel_ID { get; set; }
        public string personel_ad { get; set; }
        public string personel_soyAd { get; set; }
        public string personel_tc { get; set; }
        public string personel_tel { get; set; }
        public string personel_mail { get; set; }
        public string personel_kullanıcıAd { get; set; }
        public string personel_sifre { get; set; }
    }
}
